// generated by Fast Light User Interface Designer (fluid) version 1.0108

#ifndef gui_h
#define gui_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Menu_Button.H>
#include <FL/Fl_Spinner.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_File_Chooser.H>
#include <FL/Fl_Color_Chooser.H>

class GUI {
public:
  GUI();
  Fl_Double_Window *uiw;
  Fl_Button *l, *c, *f, *rgb;
private:
  void cb_DBG_i(Fl_Button*, void*);
  static void cb_DBG(Fl_Button*, void*);
  static Fl_Menu_Item menu_File[];
  void cb_Save_i(Fl_Menu_*, void*);
  static void cb_Save(Fl_Menu_*, void*);
  void cb_Open_i(Fl_Menu_*, void*);
  static void cb_Open(Fl_Menu_*, void*);
  void cb_New_i(Fl_Menu_*, void*);
  static void cb_New(Fl_Menu_*, void*);
  void cb_Edge_i(Fl_Button*, void*);
  static void cb_Edge(Fl_Button*, void*);
  void cb_Blur_i(Fl_Button*, void*);
  static void cb_Blur(Fl_Button*, void*);
  void cb_Brightness_i(Fl_Spinner*, void*);
  static void cb_Brightness(Fl_Spinner*, void*);
  void cb_Contrast_i(Fl_Spinner*, void*);
  static void cb_Contrast(Fl_Spinner*, void*);
  void cb_Line_i(Fl_Button*, void*);
  static void cb_Line(Fl_Button*, void*);
  void cb_Circle_i(Fl_Button*, void*);
  static void cb_Circle(Fl_Button*, void*);
  void cb_Fill_i(Fl_Button*, void*);
  static void cb_Fill(Fl_Button*, void*);
  void cb_Color_i(Fl_Button*, void*);
  static void cb_Color(Fl_Button*, void*);
public:
  void show();
  void DBG_cb();
  void new_cb();
  void save_cb();
  void open_cb();
  void edge_cb();
  void blur_cb();
  void brightness_cb(double);
  void contrast_cb(double);
  void contrast_cb();
  void line_cb();
  void circle_cb();
  void fill_cb();
  void color_cb();
};
#endif
